Repository AY2425S2-CS2103T-W09-4/tp, pull requests merged in 2025-03, with the labels that each got.

#24 Update AboutUs to be about me
  docs/AboutUs.md
  docs/team/soonami69.md
Labels: type.Chore

#36 Update Use Cases in DG
  docs/DeveloperGuide.md
Labels: type.Chore

#47 Update Wedding class
  src/main/java/seedu/address/model/WeddingPlanner.java
  src/main/java/seedu/address/model/wedding/UniqueWeddingList.java
  src/main/java/seedu/address/model/wedding/Wedding.java
Labels: type.Enhancement

#51 Fix checkstyle
  .gitignore
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/WeddingModelManager.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
Labels: priority.Low

#55 Add Persistent Storage
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/util/JsonUtil.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/WeddingPlanner.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/model/wedding/Date.java
  src/main/java/seedu/address/model/wedding/Title.java
  src/main/java/seedu/address/model/wedding/UniqueWeddingList.java
  src/main/java/seedu/address/model/wedding/Wedding.java
  src/main/java/seedu/address/storage/JsonAdaptedWedding.java
  src/main/java/seedu/address/storage/JsonSerializableWeddingPlanner.java
  src/main/java/seedu/address/storage/JsonWeddingPlannerStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/WeddingPlannerStorage.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: priority.Medium

#73 Add Guest and Staff classes
  src/main/java/seedu/address/logic/commands/wedding/CloseWeddingCommand.java
  src/main/java/seedu/address/model/person/guest/Availability.java
  src/main/java/seedu/address/model/person/guest/Guest.java
  src/main/java/seedu/address/model/person/staff/PaymentDetail.java
  src/main/java/seedu/address/model/person/staff/Staff.java
Labels: type.Enhancement, priority.Medium

#77 Fix checkstyle issues
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/wedding/HelpCommand.java
  src/main/java/seedu/address/logic/parser/WeddingPlannerParser.java
Labels: type.Chore, priority.Low

#78 Add filter command
  src/main/java/seedu/address/logic/commands/wedding/FilterByTagCommand.java
  src/main/java/seedu/address/logic/parser/WeddingPlannerParser.java
  src/main/java/seedu/address/logic/parser/wedding/FilterByTagCommandParser.java
  src/main/java/seedu/address/model/person/PersonContainsTagPredicate.java
Labels: priority.Medium

#80 Delete wedding
  src/main/java/seedu/address/logic/commands/wedding/DeleteWeddingCommand.java
  src/main/java/seedu/address/logic/commands/wedding/RemoveWeddingPersonCommand.java
  src/main/java/seedu/address/logic/parser/WeddingPlannerParser.java
  src/main/java/seedu/address/logic/parser/wedding/DeleteWeddingCommandParser.java
  src/main/java/seedu/address/logic/parser/wedding/RemoveWeddingPersonCommandParser.java
  src/main/java/seedu/address/model/WeddingModel.java
  src/main/java/seedu/address/model/WeddingModelManager.java
  src/main/java/seedu/address/model/WeddingPlanner.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/wedding/UniqueWeddingList.java
  src/main/java/seedu/address/model/wedding/Wedding.java
  src/test/java/seedu/address/logic/commands/wedding/DeleteWeddingCommandTest.java
  src/test/java/seedu/address/logic/commands/wedding/RemoveWeddingPersonCommandTest.java
Labels: priority.Medium

#79 Update UML diagram for UI
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ArchitectureDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/Ui.png
  docs/images/listCommand.png
  docs/images/openWedding.png
Labels: type.Chore, priority.Medium, severity.Medium
