Repository AY2425S2-CS2103T-W09-4/tp, pull requests merged in 2025-04, with the labels that each got.

#118 Fix sample wedding data
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.Medium, alpha-bug

#138 Fix verbose wedding display on opening selected wedding
  src/main/java/seedu/address/commons/core/LogsCenter.java
  src/main/java/seedu/address/logic/commands/wedding/OpenWeddingCommand.java
  src/main/java/seedu/address/model/wedding/Date.java
  src/main/java/seedu/address/model/wedding/Wedding.java
  src/test/java/seedu/address/model/wedding/DateTest.java
Labels: alpha-bug

#142 Fixed alpha-bugs listed
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/wedding/EditWeddingPersonCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/WeddingPlannerParser.java
  src/main/java/seedu/address/logic/parser/wedding/EditWeddingPersonCommandParser.java
  src/main/java/seedu/address/model/wedding/Date.java
  src/main/resources/view/DefaultTheme.css
  src/main/resources/view/HelpWindow.css
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/WeddingPlannerParserTest.java
  src/test/java/seedu/address/logic/parser/wedding/AddWeddingCommandParserTest.java
  src/test/java/seedu/address/model/wedding/DateTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: alpha-bug

#143 Add support to clear all weddings
  docs/UserGuide.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicMemory.java
  src/main/java/seedu/address/logic/commands/NCommand.java
  src/main/java/seedu/address/logic/commands/YCommand.java
  src/main/java/seedu/address/logic/commands/wedding/ClearAllWeddingsCommand.java
  src/main/java/seedu/address/logic/parser/NCommandParser.java
  src/main/java/seedu/address/logic/parser/WeddingPlannerParser.java
  src/main/java/seedu/address/logic/parser/YCommandParser.java
  src/main/java/seedu/address/logic/parser/wedding/ClearAllWeddingsCommandParser.java
  src/main/java/seedu/address/model/WeddingModel.java
  src/main/java/seedu/address/model/WeddingModelManager.java
Labels: type.Epic, priority.Medium
